### ISSUE TITLE
Need help and some info regarding EC Fan control 

### ISSUE THREAD

**Issue by Bhavinjain260** [BrandTime/Asus-K550J-Hackintosh#2]
Hey i recently saw that you made a commit [Added EC fan monitoring support on ASUS K550JX](https://github.com/acidanthera/VirtualSMC/pull/70/commits/4ef70fe8e8c2ff14f74c1a1dc4914f339d716be9)

i was wondering if you can help me get EC Fan monitering support on my Asus Vivobook X515JA

**Comment by BrandTime** [comment]
Certainly.
